new tutorials, sampledatasets
sunlabuiuc/PyHealth pull request #21
Opened 2022-11-15 19:35 UTC by ycq091044

2022-11-15 20:10 UTC, zzachw commented on pyhealth/datasets/base_dataset.py
> +        self.visit_to_index: Optional[Dict[str, List[int]]] = None
I think you should call _index_patient() and _index_visit() in the init. You can also add some sanity check set_task() in the BaseDataset.

2022-11-15 20:11 UTC, zzachw commented on pyhealth/datasets/base_dataset.py
> +                }
Can you elaborate on the format of the samples? I think you can move the description in Attributes/samples here.

2022-11-15 20:15 UTC, zzachw requested changes

2022-11-15 20:15 UTC, zzachw commented on pyhealth/datasets/base_dataset.py
> +    def get_all_tokens(self, key: str, sort: bool = True) -> List[str]:
Can you update this function to match BaseDataset.get_all_tokens()?

2022-11-15 20:15 UTC, zzachw commented on pyhealth/datasets/base_dataset.py
> +        self.visit_to_index: Optional[Dict[str, List[int]]] = None
I think you should call _index_patient() and _index_visit() in the init. You can also add some sanity check set_task() in the BaseDataset.

2022-11-15 20:15 UTC, zzachw commented on pyhealth/datasets/base_dataset.py
> +            Default is None.
Can you elaborate on the format of the samples in Args? I think you can move the description in Attributes/samples here.

2022-11-15 20:15 UTC, zzachw commented on pyhealth/datasets/base_dataset.py
> +    def task_stat(self) -> None:
Can you update this function to match BaseDataset.task_stat()? I think the get_label_distribution can be removed.

2022-11-15 21:52 UTC, zzachw requested changes

2022-11-15 21:52 UTC, zzachw commented on pyhealth/trainer.py
> +
These two lines seem unnecessary

2022-11-15 21:52 UTC, zzachw commented on pyhealth/trainer.py
>              scores: a dictionary of scores.
Returns need update

2022-11-15 22:02 UTC, zzachw approved these changes

2022-11-15 23:15 UTC, merged

2026-02-16 20:26 UTC, jalengg commented
Fixed in commit 2d4fbbdb. MANIFEST.in added to include all YAML config files in package distribution. Verified that all 8 config files are now included in the built package.