Team 9 Jathurshan Towards Interpretable Sleep Stage Classification Using Cross-Modal Transformers
sunlabuiuc/PyHealth pull request #224
Opened 2023-10-02 08:08 UTC by Jathurshan0330

2023-10-02 08:11 UTC, Jathurshan0330 commented
Added  task function: multi_epoch_multi_modal_sleep_staging_sleepedf_fn, Cross-modal transformer, interactive plotting to visualize interpretations and multi_epoch_multi_modal_sleep_staging_sleepedf_fn.py

2023-10-16 05:05 UTC, zlin7 requested changes
Overall great job! Please take a look at my comments, and remove code that is commented out.

2023-10-16 05:05 UTC, zlin7 commented on pyhealth/models/cross_modal_transformer.py
> +from einops import rearrange, reduce, repeat
Should add the dependency or pop up a message for the user to install this package. 

Is it possible to get rid of this dependency actually? For example, `Rearrange` can probably be achieved via `torch.permute`.

2023-10-16 05:05 UTC, zlin7 commented on pyhealth/models/cross_modal_transformer.py
> +        # Get EEG and EOG signals and slice them into 30s epochs
Can we apply this on any two types of signals? e.g. EEG + ECG? If so, maybe renaming the variables could be helpful.

2023-10-16 05:05 UTC, zlin7 commented on pyhealth/tasks/sleep_staging.py
> +
Can remove this now

2023-10-16 05:05 UTC, zlin7 commented on examples/sleep_staging_manytomany_sleepedf_cross_modal_transformer.py
> +    root="/srv/local/data/SLEEPEDF/sleep-edf-database-expanded-1.0.0/sleep-cassette",#'/home/jp65/pyhealth_hackathon/storage.googleapis.com/pyhealth/sleepedf-sample',#"/srv/local/data/SLEEPEDF/sleep-
let's clean up this path ( in particular the username)

2023-10-16 05:05 UTC, zlin7 commented on pyhealth/models/cross_modal_transformer.py
> +    def forward(self,**kwargs):
Please also handle the kwarg `embed` - see https://github.com/sunlabuiuc/PyHealth/blob/89ee19fa084f4cc0be8205eb59b82375ff9e2c69/pyhealth/models/retain.py#L364. This is for the calibration module. Thanks!

2023-10-16 05:05 UTC, zlin7 commented on pyhealth/models/cross_modal_transformer.py
> +https://colab.research.google.com/drive/1jwD5NX8cR47MRtnOW_drKIS6lP1tbWFc?usp=sharing
Please add more explanations to the tutorial

2023-10-16 05:05 UTC, zlin7 commented on pyhealth/sleep_staging_manytomany_sleepedf_cross_modal_transformer.py
Can we remove this file?

2023-10-22 05:44 UTC, Jathurshan0330 commented on pyhealth/models/cross_modal_transformer.py
> +        # Get EEG and EOG signals and slice them into 30s epochs
In the paper, it is mainly used for two signals: EEG and ECG. Due to that, I maintained the variables' names as it is also more easier to extract necessary attention weights for interpretation.

2023-10-22 05:58 UTC, Jathurshan0330 commented on pyhealth/sleep_staging_manytomany_sleepedf_cross_modal_transformer.py
It can be removed. Also, where can I mention about the colab tutorial

2023-10-23 04:00 UTC, ycq091044 commented
@Jathurshan0330 I will merge this PR to a temporary PR for local testing. Please follow Zhen's comments and finish the PR improvements if possible.

2023-10-23 04:00 UTC, merged